# ch2. ndarray 생성하기 

이번 챕터에서는 numpy에서 다차원 배열을 다루는 가장 기본인 ndarray를 직접 만들어보겠습니다.  
그리고 ndarray의 기본 조작법을 배워보겠습니다.

## ndarray 만들기

### python list를 이용해서 ndarray 생성

In [1]:
!pip install numpy


[notice] A new release of pip is available: 23.1.2 -> 23.3.1
[notice] To update, run: pip install --upgrade pip


In [2]:
import numpy as np

In [7]:
a = np.array([
    [1, 2],
    [3, 4]
])

In [8]:
a, type(a), a.shape

(array([[1, 2],
        [3, 4]]),
 numpy.ndarray,
 (2, 2))

### np.zeros
0으로 채워진 ndarray 리턴

In [17]:
a = np.zeros([3, 2, 2], dtype=np.int64)

In [18]:
a

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [19]:
type(a[0][0][0])

numpy.int64

### np.ones
1로 채워진 ndarray 리턴

In [21]:
np.ones([2, 3], dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1]])

### np.full
특정 값으로 채워진 ndarray 리턴

In [25]:
np.full([3, 2], -np.inf)

array([[-inf, -inf],
       [-inf, -inf],
       [-inf, -inf]])

### np.arange
특정 간격으로 채워진 ndarray 생성

In [28]:
np.arange(1, 9, 1)

array([1, 2, 3, 4, 5, 6, 7, 8])

### 연습문제
np.ones, np.zeros, np.fulls를 사용하여 아래 형태의 ndarray를 생성하시오.

In [29]:
np.ones([2, 2, 2], dtype=np.int64)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [30]:
np.zeros([2, 2, 2], dtype=np.int64)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [33]:
np.zeros([2, 2, 2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [31]:
np.full([3, 3], 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [32]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])