# ch5. ndarray 연산
numpy ndarray도 더하고 빼기 연산을 할 수 있습니다.

### ndarray와 숫자 (스칼라값) 간의 연산
ndarray는 숫자와 더하기, 빼기, 나누기, 곱하기가 가능합니다. 이 때, ndarray의 모든 요소들에 해당 숫자 연산이 적용됩니다.

In [27]:
import numpy as np

In [30]:
a = np.arange(1, 9, 1).reshape([2, 4])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### ndarray 간 연산
차원이 동일한 ndarray 간에는 사칙 연산이 가능합니다. 이 때는 ndarray의 동일한 인덱스끼리 연산을 수행합니다.

### numpy boolean 연산
ndarray에 부등식 연산을 수행하면 각 원소에 대해서 부등식을 만족하는지 여부를 boolean 값으로 채워준 ndarray를 리턴합니다.

이렇게 구한 boolean 값으로 채워진 ndarray는 인덱스처럼 사용할 수 있습니다.

혹은 np.where를 사용하면 True인 값의 인덱스를 구할 수 있습니다.

np.where를 통해 구한 값을 다시 인덱스로 사용할 수도 있다.

## 연습문제

ndarray 연산을 이용해서 아래와 같은 출력을 구해보세요.

In [9]:
import numpy as np

a = np.arange(1, 19, 2).reshape([3,3])
b = np.arange(2, 20, 2).reshape([3,3])
a, b

(array([[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]),
 array([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]))

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

array([[ 4, 10, 16],
       [22, 28, 34],
       [40, 46, 52]])

array([11, 13, 15, 17])

array([2, 4, 6, 8])