# ch5. ndarray 연산
numpy ndarray도 더하고 빼기 연산을 할 수 있습니다.

### ndarray와 숫자 (스칼라값) 간의 연산
ndarray는 숫자와 더하기, 빼기, 나누기, 곱하기가 가능합니다. 이 때, ndarray의 모든 요소들에 해당 숫자 연산이 적용됩니다.

In [1]:
import numpy as np

In [2]:
a = np.arange(1, 9, 1).reshape([2, 4])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
a + 3.5

array([[ 4.5,  5.5,  6.5,  7.5],
       [ 8.5,  9.5, 10.5, 11.5]])

In [7]:
a - 2

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6]])

In [8]:
a * 10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [9]:
a / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ]])

In [10]:
a % 2

array([[1, 0, 1, 0],
       [1, 0, 1, 0]])

In [13]:
type(a), type(a[0][0])

(numpy.ndarray, numpy.int64)

In [14]:
a.astype(np.int32)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)

### ndarray 간 연산
차원이 동일한 ndarray 간에는 사칙 연산이 가능합니다. 이 때는 ndarray의 동일한 인덱스끼리 연산을 수행합니다.

In [15]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
b = np.arange(9, 17, 1).reshape([2, 4])
b

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [17]:
c = np.arange(18, 26, 1)
c

array([18, 19, 20, 21, 22, 23, 24, 25])

In [18]:
a + b

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [19]:
a - b

array([[-8, -8, -8, -8],
       [-8, -8, -8, -8]])

In [20]:
a * b

array([[  9,  20,  33,  48],
       [ 65,  84, 105, 128]])

In [21]:
a % b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### numpy boolean 연산
ndarray에 부등식 연산을 수행하면 각 원소에 대해서 부등식을 만족하는지 여부를 boolean 값으로 채워준 ndarray를 리턴합니다.

In [34]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
a[[[False, False, False, False], [ True,  True,  True,  True]]]

array([[5, 6],
       [7, 8]])

In [35]:
a > 4

array([[False, False, False, False],
       [ True,  True,  True,  True]])

In [37]:
a % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True]])

이렇게 구한 boolean 값으로 채워진 ndarray는 인덱스처럼 사용할 수 있습니다.

In [38]:
a[a % 2 == 0]

array([2, 4, 6, 8])

In [39]:
a[a < 4]

array([1, 2, 3])

혹은 np.where를 사용하면 True인 값의 인덱스를 구할 수 있습니다.

In [40]:
np.where(a > 4)

(array([1, 1, 1, 1]), array([0, 1, 2, 3]))

np.where를 통해 구한 값을 다시 인덱스로 사용할 수도 있다.

In [42]:
a[np.where(a > 4)]

array([5, 6, 7, 8])

## 연습문제

ndarray 연산을 이용해서 아래와 같은 출력을 구해보세요.

In [46]:
import numpy as np

a = np.arange(1, 19, 2).reshape([3,3])
b = np.arange(2, 20, 2).reshape([3,3])
a, b

(array([[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]),
 array([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]))

In [47]:
a + b

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

In [48]:
a - b

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [49]:
a*2 + b

array([[ 4, 10, 16],
       [22, 28, 34],
       [40, 46, 52]])

array([[ 4, 10, 16],
       [22, 28, 34],
       [40, 46, 52]])

In [50]:
a[a>10]

array([11, 13, 15, 17])

array([11, 13, 15, 17])

In [51]:
b[b<10]

array([2, 4, 6, 8])

array([2, 4, 6, 8])